# Generated by Django 5.1.7 on 2025-03-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCHAT', '0003_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='status',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='status',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
