# Generated by Django 5.1.7 on 2025-03-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCHAT', '0004_rename_timestamp_status_created_at_status_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='status',
            name='file',
        ),
        migrations.AlterField(
            model_name='status',
            name='content',
            field=models.FileField(default=1, upload_to='statuses/'),
            preserve_default=False,
        ),
    ]
