# Generated by Django 5.1.7 on 2025-03-20 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCHAT', '0005_rename_created_at_status_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='user',
        ),
        migrations.AddField(
            model_name='status',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SCHAT.student'),
            preserve_default=False,
        ),
    ]
