# Generated by Django 5.1.7 on 2025-03-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SCHAT', '0006_remove_status_user_status_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
