# Generated by Django 5.1.7 on 2025-03-20 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCHAT', '0007_status_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='VideoContent',
        ),
    ]
