# Generated by Django 5.1.7 on 2025-03-21 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCHAT', '0010_message_is_seen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Call',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='NoticeBoard',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_seen',
        ),
    ]
