# Generated by Django 5.1.7 on 2025-04-09 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SCHAT', '0012_message_call_room_id_message_is_call_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='call_room_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_call_request',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_online',
        ),
        migrations.DeleteModel(
            name='CallSession',
        ),
    ]
